### ISSUE TITLE
Crystals SFT floor price 

### ISSUE THREAD

**Issue by udangijo** [JamesDiablo/genopets_tg_bot#2]
Hi, Thanks for making an amazing tool.
May I request you to change the crystals floor price from Crystals NFT to Crystals SFT'sprice.
The crystal NFTs collection will be taken down 8/31.

**Comment by JamesDiablo** [comment]
Hi. Thanks for the feedback. 
Unfortunately, MagicEden didn't develop API for SFT tokens :(
